# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}            - nom : Première interaction
  utilisations : actions/first-interaction@v1.3.0
  avec:
    # Jeton pour le référentiel. Peut être transmis à l'aide de {{ secrets.GITHUB_TOKEN }}
    jeton de dépôt :
    # Commentaire à publier sur le premier problème d'un individu
    message d'erreur : # facultatif
    # Commentaire à publier sur la première pull request d'un individu
    pr-message: # facultatif
                      - nom : Installation du SDK .NET Core
  utilisations : actions/setup-dotnet@v4.3.0
  avec:
    # Version(s) facultative(s) du SDK à utiliser. Si elle n'est pas fournie, la version global.json sera installée lorsqu'elle sera disponible. Exemples : 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
    dotnet-version: # facultatif
    # Qualité optionnelle de la construction. Les valeurs possibles sont : daily, signed, validated, preview, ga.
    dotnet-quality : # facultatif
    # Emplacement global.json facultatif, si votre global.json n'est pas situé à la racine du dépôt.
    global-json-file: # facultatif
    # Source de package facultative pour laquelle configurer l'authentification. Consultera tout NuGet.config existant à la racine du dépôt et fournira un NuGet.config temporaire à l'aide de la variable d'environnement NUGET_AUTH_TOKEN comme mot de passe ClearText
    source-url: # facultatif
    # PROPRIÉTAIRE facultatif pour l'utilisation de packages provenant d'organisations/utilisateurs du registre de packages GitHub autres que le propriétaire actuel du référentiel. Utilisé uniquement si une URL GPR est également fournie dans l'URL source
    propriétaire : # facultatif
    # Emplacement NuGet.config facultatif, si votre NuGet.config ne se trouve pas à la racine du référentiel.
    fichier de configuration : # facultatif
    # Entrée facultative pour activer la mise en cache du dossier global-packages de NuGet
    cache : # facultatif
    # Utilisé pour spécifier le chemin d'accès à un fichier de dépendances : packages.lock.json. Prend en charge les caractères génériques ou une liste de noms de fichiers pour la mise en cache de plusieurs dépendances.
    cache-dependency-path: # facultatif
                      - nom : Fermer les problèmes obsolètes
  utilisations : actions/stale@v9.1.0
  avec:
    # Jeton pour le référentiel. Peut être transmis à l'aide de `{{ secrets.GITHUB_TOKEN }}`.
    repo-token : # facultatif, la valeur par défaut est ${{ github.token }}
    # Le message à publier sur le problème lors de son marquage. Si aucun message n'est fourni, les problèmes ne seront pas marqués comme obsolètes.
    message de problème obsolète : # facultatif
    # Le message à publier sur la demande d'extraction lors de son marquage. Si aucun message n'est fourni, les demandes d'extraction ne seront pas marquées comme obsolètes.
    stale-pr-message: # facultatif
    # Le message à publier sur le problème lors de sa fermeture. Si aucun message n'est fourni, aucun commentaire ne sera publié lors de la fermeture d'un problème.
    close-issue-message: # facultatif
    # Le message à publier sur la demande d'extraction lors de sa fermeture. Si aucun message n'est fourni, aucun commentaire ne sera publié lors de la fermeture d'une demande d'extraction.
    close-pr-message: # facultatif
    # Le nombre de jours pendant lesquels un problème ou une demande d'extraction peut être marqué comme obsolète. Définissez-le sur -1 pour ne jamais marquer automatiquement les problèmes ou les demandes d'extraction comme obsolètes.
    jours-avant-période: # facultatif, la valeur par défaut est 60
    # Le nombre de jours avant qu'un problème ne soit marqué comme obsolète. Définissez-le sur -1 pour ne jamais marquer automatiquement les problèmes comme obsolètes. Remplacez l'option « jours avant l'obsolescence » concernant uniquement les problèmes.
    jours-avant-problème-obsolète : # facultatif
    # Le nombre de jours avant qu'une demande d'extraction ne soit marquée comme obsolète. Définissez-le sur -1 pour ne jamais marquer automatiquement les demandes d'extraction comme obsolètes. Remplacez l'option « days-before-stale » concernant uniquement les demandes d'extraction.
    jours-avant-pr-stale: # facultatif
    # Le nombre de jours à attendre pour fermer un problème ou une demande d'extraction après qu'il a été marqué comme obsolète. Définissez sur -1 pour ne jamais fermer les problèmes ou les demandes d'extraction obsolètes.
    jours-avant-fermeture : # facultatif, la valeur par défaut est 7
    # Le nombre de jours à attendre pour fermer un problème après qu'il a été marqué comme obsolète. Définissez-le sur -1 pour ne jamais fermer les problèmes obsolètes. Remplacez l'option « jours avant la fermeture » ​​concernant uniquement les problèmes.
    jours-avant-la-fermeture-du-problème : # facultatif
    # Le nombre de jours à attendre pour fermer une demande d'extraction après qu'elle a été marquée comme obsolète. Définissez-le sur -1 pour ne jamais fermer les demandes d'extraction obsolètes. Remplacez l'option « days-before-close » concernant uniquement les demandes d'extraction.
    jours-avant-la-clôture-du-pr : # facultatif
    # L'étiquette à appliquer lorsqu'un problème est obsolète.
    stale-issue-label : # facultatif, la valeur par défaut est Stale
    # L'étiquette à appliquer lorsqu'un problème est fermé.
    close-issue-label: # facultatif
    # Les étiquettes qui signifient qu'un problème ne peut pas être marqué comme obsolète. Séparez les étiquettes multiples par des virgules (par exemple, « label1,label2 »).
    exempt-issue-labels : # facultatif, la valeur par défaut est
    # La raison à utiliser lors de la fermeture d'un problème.
    close-issue-reason: # facultatif, la valeur par défaut est not_planned
    # L'étiquette à appliquer lorsqu'une demande d'extraction est obsolète.
    stale-pr-label : # facultatif, la valeur par défaut est Stale
    # L'étiquette à appliquer lorsqu'une demande d'extraction est fermée.
    close-pr-label: # facultatif
    # Les étiquettes qui signifient qu'une demande d'extraction est exemptée d'être marquée comme obsolète. Séparez plusieurs étiquettes par des virgules (par exemple « label1,label2 »).
    exempt-pr-labels : # facultatif, la valeur par défaut est
    # Les jalons qui signifient qu'un problème ou une demande d'extraction ne peuvent pas être marqués comme obsolètes. Séparez plusieurs jalons par des virgules (par exemple, « milestone1,milestone2 »).
    exempt-milestones : # facultatif, la valeur par défaut est
    # Les jalons qui signifient qu'un problème est exempté d'être marqué comme obsolète. Séparez plusieurs jalons par des virgules (par exemple, « milestone1,milestone2 »). Remplacez l'option « exempt-milestones » concernant uniquement les problèmes.
    exempt-issue-milestones : # facultatif, la valeur par défaut est
    # Les jalons qui signifient qu'une demande d'extraction est exemptée d'être marquée comme obsolète. Séparez plusieurs jalons par des virgules (par exemple, « milestone1,milestone2 »). Remplacez l'option « exempt-milestones » concernant uniquement les demandes d'extraction.
    exempt-pr-milestones : # facultatif, la valeur par défaut est
    # Exemptez tous les problèmes et demandes d'extraction avec des jalons d'être marqués comme obsolètes. La valeur par défaut est false.
    exempt-all-milestones : # facultatif, la valeur par défaut est false
    # Exempter tous les problèmes avec des jalons d'être marqués comme obsolètes. Remplacer l'option « exempt-all-milestones » concernant uniquement les problèmes.
    exempt-all-issue-milestones : # facultatif, la valeur par défaut est
    # Exempter toutes les demandes d'extraction avec des jalons pour qu'elles ne soient pas marquées comme obsolètes. Remplacer l'option « exempt-all-milestones » concernant uniquement les demandes d'extraction.
    exempt-all-pr-milestones : # facultatif, la valeur par défaut est
    # Seuls les problèmes ou les demandes d'extraction avec toutes ces étiquettes sont vérifiés s'ils sont obsolètes. La valeur par défaut est `` (désactivé) et peut être une liste d'étiquettes séparées par des virgules.
    only-labels: # facultatif, la valeur par défaut est
    # Seuls les problèmes ou les demandes d'extraction avec au moins une de ces étiquettes sont vérifiés s'ils sont obsolètes. La valeur par défaut est `` (désactivé) et peut être une liste d'étiquettes séparées par des virgules.
    any-of-labels : # facultatif, la valeur par défaut est
    # Seuls les problèmes avec au moins une de ces étiquettes sont vérifiés s'ils sont obsolètes. La valeur par défaut est `` (désactivé) et peut être une liste d'étiquettes séparées par des virgules. Remplacez l'option « any-of-labels » concernant uniquement les problèmes.
    any-of-issue-labels : # facultatif, la valeur par défaut est
    # Seules les demandes d'extraction avec au moins un de ces libellés sont vérifiées si elles sont obsolètes. La valeur par défaut est `` (désactivé) et peut être une liste de libellés séparés par des virgules. Remplacez l'option « any-of-labels » concernant uniquement les demandes d'extraction.
    any-of-pr-labels : # facultatif, la valeur par défaut est
    # Seuls les problèmes avec toutes ces étiquettes sont vérifiés s'ils sont obsolètes. La valeur par défaut est « [] » (désactivé) et peut être une liste d'étiquettes séparées par des virgules. Remplacez l'option « only-labels » concernant uniquement les problèmes.
    only-issue-labels: # facultatif, la valeur par défaut est
    # Seules les demandes d'extraction avec toutes ces étiquettes sont vérifiées si elles sont obsolètes. La valeur par défaut est « [] » (désactivée) et peut être une liste d'étiquettes séparées par des virgules. Remplacez l'option « only-labels » concernant uniquement les demandes d'extraction.
    only-pr-labels : # facultatif, la valeur par défaut est
    # Le nombre maximal d'opérations par exécution, utilisé pour contrôler la limitation du débit (lié à l'API GitHub CRUD).
    operations-per-run : # facultatif, la valeur par défaut est 30
    # Supprimez les étiquettes obsolètes des problèmes et des demandes d'extraction lorsqu'ils sont mis à jour ou commentés.
    remove-stale-when-updated : # facultatif, la valeur par défaut est true
    # Supprimez les étiquettes obsolètes des problèmes lorsqu'ils sont mis à jour ou commentés. Remplacez l'option « remove-stale-when-updated » concernant uniquement les problèmes.
    remove-issue-stale-when-updated: # facultatif, la valeur par défaut est
    # Supprimez les étiquettes obsolètes des demandes d'extraction lorsqu'elles sont mises à jour ou commentées. Remplacez l'option « remove-stale-when-updated » concernant uniquement les demandes d'extraction.
    remove-pr-stale-when-updated : # facultatif, la valeur par défaut est
    # Exécutez le processeur en mode débogage sans réellement effectuer d'opérations sur des problèmes en direct.
    debug-only : # facultatif, la valeur par défaut est false
    # L'ordre dans lequel obtenir les problèmes ou les demandes d'extraction. La valeur par défaut est false, ce qui est décroissant.
    croissant : # facultatif, la valeur par défaut est false
    # Supprimez la branche git après avoir fermé une demande d'extraction obsolète.
    delete-branch : # facultatif, la valeur par défaut est false
    # La date utilisée pour ignorer l'action obsolète sur le problème/la demande d'extraction créée avant elle (ISO 8601 ou RFC 2822).
    date de début : # facultatif, la valeur par défaut est
    # Les personnes chargées de la gestion des problèmes qui permettent d'éviter qu'un problème ou une demande d'extraction ne soit marqué comme obsolète. Séparez les différentes personnes chargées de la gestion des problèmes par des virgules (par exemple, « utilisateur1, utilisateur2 »).
    exempt-assignees : # facultatif, la valeur par défaut est
    # Les personnes chargées d'exempter un problème d'être marqué comme obsolète. Séparez les personnes chargées d'exempter par des virgules (par exemple, « utilisateur1, utilisateur2 »). Remplacez l'option « exempt-assignees » concernant uniquement les problèmes.
    exempt-issue-assignees : # facultatif, la valeur par défaut est
    # Les cessionnaires qui exemptent une demande d'extraction d'être marquée comme obsolète. Séparez les cessionnaires multiples par des virgules (par exemple, « utilisateur1, utilisateur2 »). Remplacez l'option « exempt-assignees » concernant uniquement les demandes d'extraction.
    exempt-pr-assignees : # facultatif, la valeur par défaut est
    # Exempter tous les problèmes et demandes d'extraction avec des cessionnaires d'être marqués comme obsolètes. La valeur par défaut est false.
    exempt-all-assignees : # facultatif, la valeur par défaut est false
    # Exempter tous les problèmes avec des cessionnaires d'être marqués comme obsolètes. Remplacer l'option « exempt-all-assignees » concernant uniquement les problèmes.
    exempt-all-issue-assignees : # facultatif, la valeur par défaut est
    # Exempter toutes les demandes d'extraction avec des cessionnaires d'être marquées comme obsolètes. Remplacer l'option « exempt-all-assignees » concernant uniquement les demandes d'extraction.
    exempt-all-pr-assignees : # facultatif, la valeur par défaut est
    # Exempter les brouillons de demandes d'extraction d'être marqués comme obsolètes. La valeur par défaut est false.
    exempt-draft-pr : # facultatif, la valeur par défaut est false
    # Afficher quelques statistiques à la fin concernant le flux de travail obsolète (uniquement lorsque les journaux sont activés).
    enable-statistics : # facultatif, la valeur par défaut est true
    # Une liste délimitée par des virgules d'étiquettes à ajouter lorsqu'un problème ou une demande d'extraction devient obsolète.
    labels-to-add-when-unstale: # facultatif, la valeur par défaut est
    # Une liste délimitée par des virgules d'étiquettes à supprimer lorsqu'un problème ou une demande d'extraction devient obsolète.
    labels-to-remove-when-stale: # facultatif, la valeur par défaut est
    # Une liste délimitée par des virgules d'étiquettes à supprimer lorsqu'un problème ou une demande d'extraction devient obsolète.
    labels-to-remove-when-unstale: # facultatif, la valeur par défaut est
    # Toute mise à jour (mise à jour/commentaire) peut réinitialiser le temps d'inactivité obsolète sur les problèmes et les demandes d'extraction.
    ignore-updates : # facultatif, la valeur par défaut est false
    # Toute mise à jour (mise à jour/commentaire) peut réinitialiser le temps d'inactivité obsolète sur les problèmes. Remplacez l'option « ignorer les mises à jour » concernant uniquement les problèmes.
    ignore-issue-updates : # facultatif, la valeur par défaut est
    # Toute mise à jour (mise à jour/commentaire) peut réinitialiser le temps d'inactivité obsolète sur les demandes d'extraction. Remplacez l'option « ignore-updates » concernant uniquement les demandes d'extraction.
    ignore-pr-updates : # facultatif, la valeur par défaut est
    # Seuls les problèmes ou les demandes d'extraction avec une personne en charge seront automatiquement marqués comme obsolètes.
    include-only-assigned : # facultatif, la valeur par défaut est false
          
